### ISSUE TITLE
レベリングシステム

### ISSUE THREAD

**Issue by sikkokuhyouma** [katai5plate/discord-had2apps-bot#2]
JavaScriptの方にレベリングシステムのライブラリがあった気がします。
https://scrapbox.io/discordjs-japan/%E7%B0%A1%E6%98%93%E7%9A%84%E3%81%AA%E3%83%AC%E3%83%99%E3%83%AB%E3%82%B7%E3%82%B9%E3%83%86%E3%83%A0%E3%81%AE%E3%82%B5%E3%83%B3%E3%83%97%E3%83%AB
URL長くてごめんなさい。
こういった感じに実装すると良さそうな気がします。
これにDBを使えば管理が楽そうな気がします。

**Comment by katai5plate** [comment]
方法論としてはわかっちゃいるが問題はそこじゃなく、
現段階で運用中のAtlas botのデータベースに入ってる各ユーザーの経験値情報をどうするかとか、
そういうメタ的な問題が主軸にあるから気軽に作れない。

**Comment by sikkokuhyouma** [comment]
なるほど・・・。
確かに引き継げたら良いんだけど、流石にAPIはないだろうから難しいところですね・・・。
